name: bdk_flutter
description: A Flutter library for the Bitcoin Development Kit(bdk) (https://bitcoindevkit.org/)
version: 0.2.1
homepage: https://github.com/LtbLightning/bdk-flutter

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.51.0
  ffi: ^2.0.1
  freezed_annotation: ^2.2.0
  freezed: ^2.2.1
  mockito: ^5.3.2
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  ffigen: ^7.2.2
  lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.bdk.f.bdk_flutter
        pluginClass: BdkPlugin
      ios:
        pluginClass: BdkPlugin