name: bdk_flutter
description: A Flutter library for the Bitcoin Development Kit(bdk) (https://bitcoindevkit.org/)
version: 0.28.0
homepage: https://github.com/LtbLightning/bdk-flutter

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ">1.75.0 <= 1.75.1"
  ffi: ^2.0.1
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  mockito: ^5.3.2
  meta: ^1.8.0
  uuid: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  ffigen: ^7.2.4
  lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.bdk.f.bdk_flutter
        pluginClass: BdkPlugin
      ios:
        pluginClass: BdkPlugin
