name: bdk_flutter
description: A Flutter library for the Bitcoin Development Kit(bdk) (https://bitcoindevkit.org/)
version: 0.29.1
homepage: https://github.com/LtbLightning/bdk-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ">1.78.0 <= 1.82.0"
  ffi: ^2.0.1
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  mockito: ^5.4.0
  meta: ^1.8.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^9.0.0
  build_runner: ^2.4.4
  lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.bdk.f.bdk_flutter
        pluginClass: BdkFlutterPlugin
      ios:
        pluginClass: BdkFlutterPlugin
