[package]
name = "rust_bdk_ffi"
version = "0.29.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]
[dev-dependencies]
assert_matches = "1.5"

[build-dependencies]
flutter_rust_bridge_codegen = { version = "= 1.78.0"  }
[dependencies]
rand = "0.8"
bdk = { version = "0.28.0", features = ["all-keys", "use-esplora-ureq", "sqlite-bundled", "rpc"] }
flutter_rust_bridge = { version = "= 1.78.0"  }
serde = "1.0.89"
serde_json = "1.0.96"
anyhow = "1.0.68"
lazy_static = "1.4.0"
tokio = { version = "1", default-features = false, features = [ "rt-multi-thread", "time", "sync" ] }
[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1